#!/usr/bin/env bash
# Installs the extcap plugin into Wireshark's per-user plugin directory.
#
#   ./extcap/install.sh
#   ./extcap/install.sh --uninstall
#
# The Windows counterpart is install.ps1. This one covers Linux and macOS,
# where the differences are real rather than cosmetic:
#
#   * Wireshark executes any executable file in the extcap directory, so the
#     .py goes in directly with a shebang -- no .bat launcher is needed. But
#     the shebang must point at THIS project's virtualenv, because the plugin
#     needs pyserial and the system python almost certainly lacks it. A
#     wrapper script is used rather than rewriting the shebang, so the file in
#     the repository stays unmodified.
#   * Serial ports belong to a group. On most Linux distributions that is
#     dialout, on Arch it is uucp; without membership the board is present and
#     unopenable, which looks exactly like a broken plugin. Checked and
#     reported rather than silently assumed.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(dirname "$here")"
plugin_name="esp32c6-sniffer"

# Wireshark reads the same location on Linux and macOS. XDG_CONFIG_HOME wins
# where it is set, which is how a user with a non-default config directory
# ends up with a plugin Wireshark never looks at.
config="${XDG_CONFIG_HOME:-$HOME/.config}/wireshark"
extcap_dir="$config/extcap"
profile_dir="$config/profiles"

venv_python="$repo/host/.venv/bin/python"
package="$repo/host/src/esp32c6_sniffer"

target_sh="$extcap_dir/$plugin_name"
target_py="$extcap_dir/$plugin_name.py"
target_lib="$extcap_dir/lib/esp32c6_sniffer"

profiles=("ESP32-C6 802.15.4" "ESP32-C6 Wi-Fi" "ESP32-C6 BLE" "ESP32-C6 Sniffer")

if [[ "${1:-}" == "--uninstall" ]]; then
    for path in "$target_sh" "$target_py" "$target_lib"; do
        if [[ -e "$path" ]]; then rm -rf "$path"; echo "removed $path"; fi
    done
    for name in "${profiles[@]}"; do
        if [[ -e "$profile_dir/$name" ]]; then
            rm -rf "$profile_dir/$name"
            echo "removed $profile_dir/$name"
        fi
    done
    echo "Uninstalled."
    exit 0
fi

if [[ ! -x "$venv_python" ]]; then
    echo "Project virtual environment not found at $venv_python" >&2
    echo "Create it with:" >&2
    echo "  cd $repo/host && python3 -m venv .venv && .venv/bin/python -m pip install -e '.[dev]'" >&2
    exit 1
fi
[[ -d "$package" ]] || { echo "Package not found at $package" >&2; exit 1; }

mkdir -p "$extcap_dir/lib"

cp "$here/$plugin_name.py" "$target_py"
echo "installed $target_py"

# The package beside the plugin, so it resolves without the repository layout.
rm -rf "$target_lib"
cp -r "$package" "$target_lib"
echo "installed $target_lib"

# Wireshark runs executables from this directory, so the entry point is a
# wrapper naming the virtualenv interpreter explicitly.
cat > "$target_sh" <<WRAPPER
#!/bin/sh
# Generated by extcap/install.sh. Re-run that script to regenerate.
exec "$venv_python" "\$(dirname "\$0")/$plugin_name.py" "\$@"
WRAPPER
chmod +x "$target_sh"
echo "installed $target_sh"

# One configuration profile per radio. Each carries an auto_switch_filter
# naming its own interface, so the right one selects itself and its filter
# buttons are the ones that can match.
old="$profile_dir/ESP32-C6 Sniffer"
if [[ -e "$old" ]]; then
    rm -rf "$old"
    echo "removed the superseded $old"
fi
if [[ -d "$repo/wireshark-profiles" ]]; then
    for dir in "$repo"/wireshark-profiles/*/; do
        name="$(basename "$dir")"
        mkdir -p "$profile_dir/$name"
        cp "$dir"* "$profile_dir/$name/"
        echo "installed $profile_dir/$name"
    done
fi

echo
echo "Installed. Verify with:"
echo "  tshark -D"
echo "Then restart Wireshark; the interfaces appear on the welcome screen."

# Serial permissions. A board that is present but unopenable looks exactly
# like a broken plugin, and the fix is not discoverable from the error.
if [[ "$(uname)" == "Linux" ]]; then
    port="$(ls /dev/ttyACM* /dev/ttyUSB* 2>/dev/null | head -n1 || true)"
    if [[ -n "$port" && ! -r "$port" ]]; then
        group="$(stat -c '%G' "$port")"
        echo
        echo "WARNING: $port belongs to group '$group' and you are not in it."
        echo "The board will be visible and impossible to open. Fix with:"
        echo "  sudo usermod -aG $group \$USER"
        echo "then log out and back in -- a new shell is not enough."
    fi
fi
