# Installs the extcap plugin into Wireshark's per-user plugin directory.
#
#   .\extcap\install.ps1
#   .\extcap\install.ps1 -Uninstall
#
# Installs to %APPDATA%\Wireshark\extcap rather than the Program Files copy:
# it needs no administrator rights and survives a Wireshark upgrade.
#
# Wireshark executes .bat or .exe from that directory, never .py, so a launcher
# is generated pointing at this project's virtual environment. That environment
# supplies pyserial, which Wireshark's own Python (if any) would not have.

param(
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$repo       = Split-Path -Parent $PSScriptRoot
$extcapDir  = Join-Path $env:APPDATA 'Wireshark\extcap'
$pluginName = 'esp32c6-sniffer'
$venvPython = Join-Path $repo 'host\.venv\Scripts\python.exe'
$package    = Join-Path $repo 'host\src\esp32c6_sniffer'

$targetPy  = Join-Path $extcapDir "$pluginName.py"
$targetBat = Join-Path $extcapDir "$pluginName.bat"
$targetLib = Join-Path $extcapDir 'lib\esp32c6_sniffer'

if ($Uninstall) {
    $profileRoot = Join-Path $env:APPDATA 'Wireshark\profiles'
    $profiles = @('ESP32-C6 802.15.4', 'ESP32-C6 Wi-Fi', 'ESP32-C6 BLE',
                  'ESP32-C6 Sniffer')   # the last is the superseded single one
    $paths = @($targetPy, $targetBat, $targetLib)
    $paths += $profiles | ForEach-Object { Join-Path $profileRoot $_ }
    foreach ($p in $paths) {
        if (Test-Path $p) { Remove-Item $p -Recurse -Force; Write-Host "removed $p" }
    }
    Write-Host "Uninstalled." -ForegroundColor Green
    return
}

if (-not (Test-Path $venvPython)) {
    throw "Project virtual environment not found at $venvPython. Create it with: cd host; py -m venv .venv; .\.venv\Scripts\python.exe -m pip install -e `".[dev]`""
}
if (-not (Test-Path $package)) { throw "Package not found at $package" }

New-Item -ItemType Directory -Force -Path $extcapDir | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $targetLib) | Out-Null

Copy-Item (Join-Path $PSScriptRoot "$pluginName.py") $targetPy -Force
Write-Host "installed $targetPy"

# Copy the package next to the plugin so it resolves without the repository
# layout. The plugin adds its own lib/ directory to the import path.
if (Test-Path $targetLib) { Remove-Item $targetLib -Recurse -Force }
Copy-Item $package $targetLib -Recurse -Force
Write-Host "installed $targetLib"

@"
@echo off
rem Generated by extcap\install.ps1. Re-run that script to regenerate.
"$venvPython" "%~dp0$pluginName.py" %*
"@ | Set-Content -Path $targetBat -Encoding ascii
Write-Host "installed $targetBat"

# Wireshark configuration profiles: columns for the radio metadata, colouring
# rules and filter buttons. Without them a capture is dissected correctly but
# reads poorly, since channel, signal strength and link quality are only
# visible by clicking into each frame.
#
# One per radio, because a filter button belongs to the profile rather than to
# the interface: a single shared profile put Zigbee, Thread and 11ax buttons
# on a BLE capture, where none of them can ever match. Each carries an
# auto_switch_filter naming its own interface, so the right one selects itself.
$profileRoot = Join-Path $env:APPDATA 'Wireshark\profiles'

# The superseded single profile matched every interface, so leaving it in
# place would have it competing with all three.
$old = Join-Path $profileRoot 'ESP32-C6 Sniffer'
if (Test-Path $old) {
    Remove-Item $old -Recurse -Force
    Write-Host "removed the superseded '$old'"
}

$profilesSrc = Join-Path $repo 'wireshark-profiles'
if (Test-Path $profilesSrc) {
    foreach ($dir in Get-ChildItem $profilesSrc -Directory) {
        $dst = Join-Path $profileRoot $dir.Name
        New-Item -ItemType Directory -Force -Path $dst | Out-Null
        Copy-Item (Join-Path $dir.FullName '*') $dst -Force
        Write-Host "installed $dst"
    }
}

Write-Host ""
Write-Host "Installed. Verify with:" -ForegroundColor Green
Write-Host '  & "C:\Program Files\Wireshark\tshark.exe" -D'
Write-Host "Then restart Wireshark; the interface appears on the welcome screen."
Write-Host ""
Write-Host "A profile per radio is installed, and the matching one selects itself"
Write-Host "for each capture, so its filter buttons are the ones that can match."
Write-Host "If it does not, right-click the profile area at the bottom-right of"
Write-Host "Wireshark's status bar and choose it."
Write-Host "Enable the toolbar: View menu, Interface Toolbars."
